

<form class="row g-3" method="post" action="<?=link.'usuarios/add'?>">

 <?php

          if(isset($_SESSION['tp'])){
            
            echo '<div class="col-md-12">';

              if($_SESSION['tp'] == 'sucesso'){

                  echo '<div class="alert alert-success" role="alert">
                        '.$_SESSION['txt'].'
                      </div>';
              }else{

                  echo '<div class="alert alert-danger" role="alert">
                        '.$_SESSION['txt'].'
                      </div>';
              }
              echo '</div>';

            unset($_SESSION['tp']);
            unset($_SESSION['txt']);
          }

 ?>
  <div class="col-md-6">
    <label for="nome" class="form-label">Nome</label>
    <input type="text" class="form-control" id="nome" name="nome" required>
  </div>
  <div class="col-md-6">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control" id="email" name="email" required>
  </div>
  <div class="col-md-12">
    <label for="passe" class="form-label">Palavra Passe</label>
    <input type="password" class="form-control" id="passe" name="passe" required>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
</form>